drivers: pci: fix irq handling in pci-msm-msi.c
Originally got this warning:
drivers/pci/host/pci-msm-msi.c:511:41: error: incompatible pointer types passing 'void (struct irq_desc )' to parameter of type 'irq_flow_handler_t' (aka '_Bool ()(struct irq_desc *)') [-Werror,-Wincompatible-pointer-types]
irq_set_chained_handler_and_data(irq, msm_msi_snps_handler,
^~~~~~~~~~~~~~~~~~~~
include/linux/irq.h:656:71: note: passing argument to parameter 'handle' here
irq_set_chained_handler_and_data(unsigned int irq, irq_flow_handler_t handle,
^
drivers/pci/host/pci-msm-msi.c:555:41: error: incompatible pointer types passing 'void (struct irq_desc )' to parameter of type 'irq_flow_handler_t' (aka '_Bool ()(struct irq_desc *)') [-Werror,-Wincompatible-pointer-types]
irq_set_chained_handler_and_data(irq, msm_msi_qgic_handler,
^~~~~~~~~~~~~~~~~~~~
include/linux/irq.h:656:71: note: passing argument to parameter 'handle' here
irq_set_chained_handler_and_data(unsigned int irq, irq_flow_handler_t handle,

Warning is legit, irq_flow_handler_t has type bool.
you can see from a common irq_flow_handler_t,
handle_level_irq in kernel/irq/chip.c,
that the return value should be true if it handled the irq,
and false if otherwise.

From kernel/irq/irqdesc.c:
 * generic_handle_irq - Invoke the handler for a particular irq
...
 * returns:
 *      negative on error
 *      0 when the interrupt handler was not called
 *      1 when the interrupt handler was called

Bug: 124912098
Change-Id: Ib5deb99c1edfca7b9ce8c68a02b6119000afde11